#!/bin/bash
set -e

# Run the Lovable AI build
npm run build

# Remove Wrangler deploy config (Pages can't use it)
rm -rf .wrangler

# Fix the wrangler.json generated by the Cloudflare Vite plugin
# Remove fields that Pages doesn't support (main, triggers, no_bundle, minify, assets)
# Keep: compatibility_date, compatibility_flags, pages_build_output_dir
node -e "
const f = 'dist/client/wrangler.json';
const j = JSON.parse(require('fs').readFileSync(f, 'utf8'));
delete j.main;
delete j.triggers;
delete j.no_bundle;
delete j.minify;
delete j.assets;
delete j.name;
require('fs').writeFileSync(f, JSON.stringify(j, null, 2));
"
