/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as TradeInRouteImport } from './routes/trade-in'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as FinancingRouteImport } from './routes/financing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InventoryStkRouteImport } from './routes/inventory.$stk'

const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeInRoute = TradeInRouteImport.update({
  id: '/trade-in',
  path: '/trade-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancingRoute = FinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryStkRoute = InventoryStkRouteImport.update({
  id: '/$stk',
  path: '/$stk',
  getParentRoute: () => InventoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/inventory/$stk': typeof InventoryStkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/inventory/$stk': typeof InventoryStkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/financing': typeof FinancingRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/reviews': typeof ReviewsRoute
  '/trade-in': typeof TradeInRoute
  '/warranty': typeof WarrantyRoute
  '/inventory/$stk': typeof InventoryStkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/financing'
    | '/inventory'
    | '/reviews'
    | '/trade-in'
    | '/warranty'
    | '/inventory/$stk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/financing'
    | '/inventory'
    | '/reviews'
    | '/trade-in'
    | '/warranty'
    | '/inventory/$stk'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/financing'
    | '/inventory'
    | '/reviews'
    | '/trade-in'
    | '/warranty'
    | '/inventory/$stk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FinancingRoute: typeof FinancingRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  ReviewsRoute: typeof ReviewsRoute
  TradeInRoute: typeof TradeInRoute
  WarrantyRoute: typeof WarrantyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-in': {
      id: '/trade-in'
      path: '/trade-in'
      fullPath: '/trade-in'
      preLoaderRoute: typeof TradeInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financing': {
      id: '/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof FinancingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$stk': {
      id: '/inventory/$stk'
      path: '/$stk'
      fullPath: '/inventory/$stk'
      preLoaderRoute: typeof InventoryStkRouteImport
      parentRoute: typeof InventoryRoute
    }
  }
}

interface InventoryRouteChildren {
  InventoryStkRoute: typeof InventoryStkRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryStkRoute: InventoryStkRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FinancingRoute: FinancingRoute,
  InventoryRoute: InventoryRouteWithChildren,
  ReviewsRoute: ReviewsRoute,
  TradeInRoute: TradeInRoute,
  WarrantyRoute: WarrantyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
